### ISSUE TITLE
feature: grayscaling

### ISSUE THREAD

**Issue by emicklei** [btastic/flutter_native_image#35]
Would you accept a PR that adds the possibility to grayscale the image (after scaling) ?

**Comment by btastic** [comment]
This library targets the main problem that the https://github.com/brendan-duncan/image library has: It can take a long time to decode an image in dart.

I appreciate that you would like to contribute to this library. But I don't want this library to be some "all-in-one" solution.

You can always use the resizing feature of this library in conjunction with https://github.com/brendan-duncan/image since it already has a grayscale function.

Thank you
